# Generated by Django 5.0.1 on 2024-02-02 06:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0021_hospitalstaffadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalstaffadmin',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
