# Generated by Django 5.0.1 on 2024-02-02 10:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0025_rename_hospitalstaffadmin_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staff',
            new_name='HospitalStaffAdmin',
        ),
    ]
