# Generated by Django 5.0.1 on 2024-02-05 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0026_rename_staff_hospitalstaffadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254, validators=[django.core.validators.EmailValidator()]),
            preserve_default=False,
        ),
    ]
