# Generated by Django 5.0.2 on 2024-02-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0030_rename_admitdate_patient_admit_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='assigned_doctor_id',
            field=models.PositiveIntegerField(default=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Unspecify', 'Unspecify'), ('Male', 'Male'), ('Female', 'Female')], default='Choose your Sex', max_length=10),
        ),
    ]
