# Generated by Django 5.0.2 on 2024-02-09 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0031_alter_patient_assigned_doctor_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='admit_date',
            new_name='admitDate',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='assigned_doctor_id',
            new_name='assignedDoctorId',
        ),
    ]
