# Generated by Django 5.0.2 on 2024-02-09 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0033_rename_admitdate_patient_admit_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='assigned_doctor_id',
        ),
    ]
