# Generated by Django 5.0.2 on 2024-02-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0034_remove_patient_assigned_doctor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='assigned_doctor_id',
            field=models.PositiveIntegerField(default=40),
            preserve_default=False,
        ),
    ]
