# Generated by Django 5.0.2 on 2024-02-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0035_patient_assigned_doctor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='assigned_doctor',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
