# Generated by Django 5.0.2 on 2024-02-11 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0036_patient_assigned_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
    ]
