# Generated by Django 5.0.2 on 2024-02-11 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0038_patient_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
    ]
