# Generated by Django 5.0.2 on 2024-02-27 09:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0047_insurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='license_num',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='License number must be 7 digits.', regex='^\\d{7}$')]),
        ),
    ]
