# Generated by Django 5.0.2 on 2024-03-10 08:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0048_doctor_license_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='mobile',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Provide a valid Contact Number (e,g: 09172464146 or +639172464146)', regex='(^(\\+)(\\d){12}$)|(^\\d{11}$)')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='admit_date',
            field=models.DateField(),
        ),
    ]
